### ISSUE TITLE
Do we need to insert figures?

### ISSUE THREAD

**Issue by ohoelske** [ahodelin/ScienceWork#12]
Did we discuss this already?

**Comment by fphans** [comment]
there is a figure on the titelpage now

**Comment by fphans** [comment]
don´t tell me you need more figures

**Comment by ohoelske** [comment]
Creative, but I highly doubt that this is appropriate.

**Comment by fphans** [comment]
inappropriate is the new political correct

**Comment by ohoelske** [comment]
No, honestly, did we speak about this with Martin and Dagmar? Technically we have the figures ready and implementing them in the text could be done. So we have something to refer to in the results section, no? I am not sure. But I am also afraid to ask, because if we do so, we will definitively have to do it.

**Comment by ohoelske** [comment]
I guess the best solution would be adding an additional PDF with the figures and legends as attachement. So that would basically be the SBGN and some reproduced figures. For them I already generated PDFs.
https://github.com/ahodelin/Bachmann_Archive/blob/main/result/Fig3/Fig3_tellurium_2021-07-03.v1.pdf

**Comment by fphans** [comment]
ok what figuers do we have? we have the result figures of you and jessi (grp 4) and the overview figure from the combine webpage. which would you choose?

**Comment by ohoelske** [comment]
I have to check in the folder, too long ago. I remember that I made PDFs with legends for the main reproduced figures (3, 4, 5 and Supp 9), so these I guess we can include. But I guess we should double check with Dagmar.

**Comment by fphans** [comment]
wieso würdest du da dagmar fragen wollen?

**Comment by ohoelske** [comment]
Ich hatte konstruktives Feedback erhofft.Wir können es auch einfach als Appendix an den Text schicken. Also PDF Hausaufgabe + PDF Abbildungen (Abbildung 1 von mir aus das SBGN und Abbildung 2 die reproduzierten Abbildungen), das kann ich morgen machen. Ich fände das gut, dann kann man die Results auch darauf beziehen. Aber ich lasse mich auch überstimmen 👯‍♂️

**Comment by fphans** [comment]
guter vorschlag, jetzt feierabend

**Comment by ohoelske** [comment]
Ok, wir schreiben morgen ;-)

**Comment by ahodelin** [comment]
Moin, 
wir werden kein Nobelpreis bekommen, das ist nur eine Prüfung, runter von Gas 😉

Enviado desde mi iPhone

**Comment by ohoelske** [comment]
Ok, Chef :)

**Comment by ahodelin** [comment]
Buenos días!!!

ich denke die Bilder und Graphen sollten in einem extra pdf sein, da A, zu viele sind B ich glaube, es gibt nicht genug Zeit um alle zu beschreiben, und C brauchen wir überhaupt Bilder im Paper?

Hasta la vista!!

**Comment by fphans** [comment]
Also stellt Ihr euch ein "supplement" vor?

**Comment by fphans** [comment]
discussion im meeting:
pdf im anhang, referenziert im text (link oder pdf)
fig 1 sbgn
fig 2 modellierungs graphen
