### ISSUE TITLE
Final version

### ISSUE THREAD

**Issue by ohoelske** [ahodelin/ScienceWork#14]
Please all go through this version 6848cd3 and finally approve the manuscript.

**Comment by fphans** [comment]
Approved! Thanks for revising

**Comment by fphans** [comment]
Hand in today?

**Comment by ahodelin** [comment]
I have made some changes, please look at the other issues

**Comment by ohoelske** [comment]
@fphans ; thanks and fine for me
@ahodelin ; Thanks for updating all the acronyms, forgot about that yesterday during writing.

**Comment by fphans** [comment]
did we hand in ?

**Comment by fphans** [comment]
ok habs jetzt nochmal hochgeladen zur sicherheit
