### ISSUE TITLE
Only pdf files in tables

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/ScienceWork#16]
Hello,

I have deleted the docx-files in the folder tables because these have the same information as the pdf-files and... a doc(x) is the same as to write an exam with pencil :-)

**Comment by ohoelske** [comment]
I would leave them there in case we have to hand them in in docx or open format, some journals require this.

**Comment by ahodelin** [comment]
I added the docx file of tables again: see comment of @ohoelske above
