### ISSUE TITLE
Tables and figures in appendices

### ISSUE THREAD

**Issue by ahodelin** [ahodelin/ScienceWork#17]
Hello,
I have inserted the tables and figures as supplementary materials into the appendices. Please review.

**Comment by ohoelske** [comment]
Hi Abel, I don't find the supplementary materials as .tex file.

**Comment by ohoelske** [comment]
There is a numbering issue. Table 1 should be the selection of experiments, Table 2 the repro score card.

**Comment by ahodelin** [comment]
Hi Oli, that is in the 7appendices.tex as in the guideline line (STARE-HI)
presented is.

**Comment by ohoelske** [comment]
Thanks
