### ISSUE TITLE
minor layout 1

### ISSUE THREAD

**Issue by fphans** [ahodelin/ScienceWork#6]
"et al" als \textit{} oder normal?

**Comment by ahodelin** [comment]
Dadurch das Latein ist, sollte es kursiv sein, wie die wissenschaftlichen Namen 

Enviado desde mi iPhone

**Comment by fphans** [comment]
gut ich machs mal einheitlich

**Comment by fphans** [comment]
scheint so zu passen 

I do like it et al.
