### ISSUE TITLE
doi creation

### ISSUE THREAD

**Issue by fphans** [ahodelin/ScienceWork#7]
sollen wir für das bachman git und die gits aus dem fuenfgeldkurs dois generieren? dann können wir das alles besser zitieren und referenzeiren? ginge z.b über zenodo

**Comment by ahodelin** [comment]
Gute Idee!!!

**Comment by fphans** [comment]
was denkst Du @ohoelske ?

**Comment by fphans** [comment]
https://guides.github.com/activities/citable-code/

**Comment by ohoelske** [comment]
Von mir aus OK, vorausg. Änderungen sind noch möglich.

**Comment by ahodelin** [comment]
_Habemus_ doi!!! 
- url: https://github.com/ahodelin/Bachmann_Archive/tree/v1.01.10.2021 (1. Release)
 - cc04 Lizenz
 - alle Authoren des initialen Projekts sind dabei
 - open acces
 - doi: https://doi.org/10.5281/zenodo.5543360
 
Wir sind Promis!!!

Für die repo von Maximilian sollte er das machen, weil ich nicht der eigentummer bin.

**Comment by fphans** [comment]
great, thanks! Only Andrea might be looking for an extra "S". 
Can we add the ORCID as well?

**Comment by ahodelin** [comment]
Ooops!!!

you can include the ORCID

**Comment by fphans** [comment]
https://zenodo.org/record/4667703

**Comment by fphans** [comment]
can U add this with your editing rights? I seem not be able to claim this somewhere under my account...

**Comment by ahodelin** [comment]
Andreas hat sein S bekommen, ich habe es überall geändert

**Comment by ahodelin** [comment]
it is on https://github.com/ahodelin/ScienceWork/tree/main/supplentary_dokuments

**Comment by fphans** [comment]
ne sorry ich meinte das nur als beispiel für die ORCID in Zenodo. Das Dokuemnt selbst braucehnw ir hier glaube ich nicht.

**Comment by ahodelin** [comment]
Ok!!

**Comment by fphans** [comment]
Ich meinte die IDs im zenodo hinzufügen...

**Comment by ahodelin** [comment]
Ja, ich bin dabei, ich fühge Dagmar auch dabei, sie hatte die Idee für die Aufgabe

**Comment by ahodelin** [comment]
schon gemacht
